package actions

import (
	"fmt"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/gobuffalo/x/responder"
	"net/http"
	"relay_pi/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Pin)
// DB Table: Plural (pins)
// Resource: Plural (Pins)
// Path: Plural (/pins)
// View Template Folder: Plural (/templates/pins/)

// PinsResource is the resource for the Pin model
type PinsResource struct {
	buffalo.Resource
}

// List gets all Pins. This function is mapped to the path
// GET /pins
func (v PinsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	pins := &models.Pins{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	//q := tx.PaginateFromParams(c.Params())

	// Retrieve all Pins from the DB
	if err := tx.All(pins); err != nil {
		return err
	}

	return c.Render(200, r.JSON(pins))

	//return responder.Wants("html", func (c buffalo.Context) error {
	//  // Add the paginator to the context so it can be used in the template.
	//  c.Set("pagination", q.Paginator)
	//
	//  c.Set("pins", pins)
	//  return c.Render(http.StatusOK, r.HTML("/pins/index.plush.html"))
	//}).Wants("json", func (c buffalo.Context) error {
	//  return c.Render(200, r.JSON(pins))
	//}).Wants("xml", func (c buffalo.Context) error {
	//  return c.Render(200, r.XML(pins))
	//}).Respond(c)
}

// Show gets the data for one Pin. This function is mapped to
// the path GET /pins/{pin_id}
func (v PinsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Pin
	pin := &models.Pin{}

	// To find the Pin the parameter pin_id is used.
	if err := tx.Find(pin, c.Param("pin_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("pin", pin)

		return c.Render(http.StatusOK, r.HTML("/pins/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(pin))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(pin))
	}).Respond(c)
}

// New renders the form for creating a new Pin.
// This function is mapped to the path GET /pins/new
func (v PinsResource) New(c buffalo.Context) error {
	c.Set("pin", &models.Pin{})

	return c.Render(http.StatusOK, r.HTML("/pins/new.plush.html"))
}

// Create adds a Pin to the DB. This function is mapped to the
// path POST /pins
func (v PinsResource) Create(c buffalo.Context) error {
	// Allocate an empty Pin
	pin := &models.Pin{}

	// Bind pin to the html form elements
	if err := c.Bind(pin); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(pin)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("pin", pin)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/pins/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "pin.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/pins/%v", pin.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(pin))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(pin))
	}).Respond(c)
}

// Edit renders a edit form for a Pin. This function is
// mapped to the path GET /pins/{pin_id}/edit
func (v PinsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Pin
	pin := &models.Pin{}

	if err := tx.Find(pin, c.Param("pin_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("pin", pin)
	return c.Render(http.StatusOK, r.HTML("/pins/edit.plush.html"))
}

// Update changes a Pin in the DB. This function is mapped to
// the path PUT /pins/{pin_id}
func (v PinsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Pin
	pin := &models.Pin{}

	if err := tx.Find(pin, c.Param("pin_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Pin to the html form elements
	if err := c.Bind(pin); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(pin)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("pin", pin)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/pins/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "pin.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/pins/%v", pin.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(pin))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(pin))
	}).Respond(c)
}

// Destroy deletes a Pin from the DB. This function is mapped
// to the path DELETE /pins/{pin_id}
func (v PinsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Pin
	pin := &models.Pin{}

	// To find the Pin the parameter pin_id is used.
	if err := tx.Find(pin, c.Param("pin_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(pin); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "pin.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/pins")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(pin))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(pin))
	}).Respond(c)
}
